# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMBdRBHj5Gnna-pJdJ56d4V-nm-uohpi
"""

import streamlit as st
import random

# 魚データ構造
fish_data = {
    "湖": {
        "春": {
            "晴れ": [
                {"name": "ワカサギ", "image": "images/wakasagi.jpg", "rare": False},
                {"name": "フナ", "image": "images/funa.jpg", "rare": False}
            ],
            "雨": [
                {"name": "ナマズ", "image": "images/namazu.jpg", "rare": False},
                {"name": "ドジョウ", "image": "images/dojo.jpg", "rare": False}
            ]
        },
        "夏": {
            "晴れ": [
                {"name": "ブラックバス", "image": "images/bass.jpg", "rare": False}
            ],
            "雨": [
                {"name": "ウナギ", "image": "images/unagi.jpg", "rare": False}
            ]
        }
    }
}

rare_fish = [
    {"name": "リュウグウノツカイ", "image": "images/ryugu.jpg", "rare": True},
    {"name": "シーラカンス", "image": "images/coelacanth.jpg", "rare": True}
]

# 初期化
if "zukan" not in st.session_state:
    st.session_state.zukan = {}

# タイトル
st.title("🎣 魚釣りゲーム")

# 場所 → 季節 → 天気 の順に選択肢を表示
location = st.selectbox("📍 場所を選んでください", list(fish_data.keys()))
season = st.selectbox("🌸 季節を選んでください", list(fish_data[location].keys()))
weather = st.selectbox("🌦 天気を選んでください", list(fish_data[location][season].keys()))

# ボタンで釣り開始
if st.button("🎣 釣る！"):
    if random.random() < 0.05:
        fish = random.choice(rare_fish)
        st.balloons()
        st.success(f"✨✨ 超レア！『{fish['name']}』を釣り上げた！ ✨✨")
    else:
        candidates = fish_data[location][season][weather]
        fish = random.choice(candidates)
        st.info(f"{fish['name']} を釣りました！")

    st.image(fish["image"], width=300)

    # 図鑑に登録
    if fish["name"] not in st.session_state.zukan:
        st.session_state.zukan[fish["name"]] = fish["image"]
        st.write(f"📖 『{fish['name']}』を図鑑に登録しました！")

# 図鑑の表示
with st.expander("🐠 図鑑を見る"):
    for name, image in st.session_state.zukan.items():
        st.write(f"📘 {name}")
        st.image(image, width=200)