# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMBdRBHj5Gnna-pJdJ56d4V-nm-uohpi
"""

import streamlit as st
import random

# --- 場所リスト ---
locations = [
    "上流", "中流", "下流", "河口",
    "東京湾", "太平洋", "日本海", "瀬戸内海", "相模湾",
    "オホーツク海", "東シナ海", "玄界灘", "大間", "五島列島",
    "積丹半島", "女川港", "大洗港", "城ヶ島", "沼津港",
    "串本", "室戸岬", "枕崎", "糸満漁港"
]

seasons = ["春", "夏", "秋", "冬"]
weathers = ["晴れ", "雨", "曇り"]

# --- 魚データ ---
fish_data = {
    "上流": {
        "春": {"晴れ": ["イワナ"], "雨": ["ヤマメ"], "曇り": ["ニジマス"]},
        "夏": {"晴れ": ["アマゴ"], "雨": ["イワナ"], "曇り": ["ヤマメ"]},
        "秋": {"晴れ": ["ヤマメ"], "雨": ["ニジマス"], "曇り": ["アマゴ"]},
        "冬": {"晴れ": ["イワナ"], "雨": ["ニジマス"], "曇り": ["ヤマメ"]},
    },
    "中流": {
        "春": {"晴れ": ["オイカワ"], "雨": ["フナ"], "曇り": ["ウグイ"]},
        "夏": {"晴れ": ["ナマズ"], "雨": ["フナ"], "曇り": ["オイカワ"]},
        "秋": {"晴れ": ["ウグイ"], "雨": ["ナマズ"], "曇り": ["フナ"]},
        "冬": {"晴れ": ["フナ"], "雨": ["オイカワ"], "曇り": ["ナマズ"]},
    },
    "下流": {
        "春": {"晴れ": ["ボラ"], "雨": ["スズキ"], "曇り": ["ハゼ"]},
        "夏": {"晴れ": ["スズキ"], "雨": ["ハゼ"], "曇り": ["ボラ"]},
        "秋": {"晴れ": ["ハゼ"], "雨": ["ボラ"], "曇り": ["スズキ"]},
        "冬": {"晴れ": ["ボラ"], "雨": ["ハゼ"], "曇り": ["スズキ"]},
    },
    "河口": {
        "春": {"晴れ": ["シーバス"], "雨": ["クロダイ"], "曇り": ["ハゼ"]},
        "夏": {"晴れ": ["スズキ"], "雨": ["クロダイ"], "曇り": ["キス"]},
        "秋": {"晴れ": ["ハゼ"], "雨": ["クロダイ"], "曇り": ["シーバス"]},
        "冬": {"晴れ": ["シーバス"], "雨": ["ハゼ"], "曇り": ["ボラ"]},
    },
    "東京湾": {
        "春": {"晴れ": ["アジ"], "雨": ["メバル"], "曇り": ["カサゴ"]},
        "夏": {"晴れ": ["シーバス"], "雨": ["タチウオ"], "曇り": ["サバ"]},
        "秋": {"晴れ": ["イナダ"], "雨": ["カマス"], "曇り": ["カレイ"]},
        "冬": {"晴れ": ["メバル"], "雨": ["アイナメ"], "曇り": ["ヒラメ"]},
    },
    "太平洋": {
        "春": {"晴れ": ["マダイ"], "雨": ["アジ"], "曇り": ["サバ"]},
        "夏": {"晴れ": ["カツオ"], "雨": ["シイラ"], "曇り": ["ブリ"]},
        "秋": {"晴れ": ["サワラ"], "雨": ["マグロ"], "曇り": ["ヒラマサ"]},
        "冬": {"晴れ": ["ヒラメ"], "雨": ["マダイ"], "曇り": ["タチウオ"]},
    },
    "日本海": {
        "春": {"晴れ": ["アジ"], "雨": ["メバル"], "曇り": ["カレイ"]},
        "夏": {"晴れ": ["ホッケ"], "雨": ["サクラマス"], "曇り": ["アキアジ"]},
        "秋": {"晴れ": ["イナダ"], "雨": ["カマス"], "曇り": ["カワハギ"]},
        "冬": {"晴れ": ["カレイ"], "雨": ["ソイ"], "曇り": ["アイナメ"]},
    },
    "瀬戸内海": {
        "春": {"晴れ": ["マダイ"], "雨": ["メバル"], "曇り": ["カサゴ"]},
        "夏": {"晴れ": ["アジ"], "雨": ["タチウオ"], "曇り": ["ハモ"]},
        "秋": {"晴れ": ["メジナ"], "雨": ["イサキ"], "曇り": ["アイゴ"]},
        "冬": {"晴れ": ["カサゴ"], "雨": ["メバル"], "曇り": ["マダイ"]},
    },
    "相模湾": {
        "春": {"晴れ": ["シマアジ"], "雨": ["カツオ"], "曇り": ["アジ"]},
        "夏": {"晴れ": ["ブリ"], "雨": ["ヒラマサ"], "曇り": ["イナダ"]},
        "秋": {"晴れ": ["サバ"], "雨": ["タチウオ"], "曇り": ["シーバス"]},
        "冬": {"晴れ": ["ヒラメ"], "雨": ["メバル"], "曇り": ["カレイ"]},
    },
    "オホーツク海": {
        "春": {"晴れ": ["ホッケ"], "雨": ["カレイ"], "曇り": ["ニシン"]},
        "夏": {"晴れ": ["カレイ"], "雨": ["ホッケ"], "曇り": ["サケ"]},
        "秋": {"晴れ": ["アキアジ"], "雨": ["ホッケ"], "曇り": ["カラフトマス"]},
        "冬": {"晴れ": ["カレイ"], "雨": ["ホッケ"], "曇り": ["ソイ"]},
    },
    "東シナ海": {
        "春": {"晴れ": ["ミーバイ"], "雨": ["アジ"], "曇り": ["タマン"]},
        "夏": {"晴れ": ["ガーラ"], "雨": ["ミーバイ"], "曇り": ["カツオ"]},
        "秋": {"晴れ": ["ミーバイ"], "雨": ["アジ"], "曇り": ["ブリ"]},
        "冬": {"晴れ": ["ミーバイ"], "雨": ["アオリイカ"], "曇り": ["ヒラメ"]},
    },
    "玄界灘": {
        "春": {"晴れ": ["ヒラマサ"], "雨": ["ブリ"], "曇り": ["アジ"]},
        "夏": {"晴れ": ["カツオ"], "雨": ["ブリ"], "曇り": ["サバ"]},
        "秋": {"晴れ": ["ヒラマサ"], "雨": ["サワラ"], "曇り": ["アオリイカ"]},
        "冬": {"晴れ": ["ヒラメ"], "雨": ["メジナ"], "曇り": ["シマアジ"]},
    },
    "大間": {
        "春": {"晴れ": ["マグロ"], "雨": ["ホッケ"], "曇り": ["サバ"]},
        "夏": {"晴れ": ["マグロ"], "雨": ["カツオ"], "曇り": ["ブリ"]},
        "秋": {"晴れ": ["マグロ"], "雨": ["サワラ"], "曇り": ["イナダ"]},
        "冬": {"晴れ": ["ホッケ"], "雨": ["カレイ"], "曇り": ["ヒラメ"]},
    },
    "五島列島": {
        "春": {"晴れ": ["イサキ"], "雨": ["メジナ"], "曇り": ["カツオ"]},
        "夏": {"晴れ": ["ヒラマサ"], "雨": ["ブリ"], "曇り": ["シイラ"]},
        "秋": {"晴れ": ["サバ"], "雨": ["カマス"], "曇り": ["タチウオ"]},
        "冬": {"晴れ": ["メジナ"], "雨": ["カサゴ"], "曇り": ["アオリイカ"]},
    },
    "積丹半島": {
        "春": {"晴れ": ["ニシン"], "雨": ["ホッケ"], "曇り": ["カレイ"]},
        "夏": {"晴れ": ["ホッケ"], "雨": ["ニシン"], "曇り": ["サケ"]},
        "秋": {"晴れ": ["アキアジ"], "雨": ["カレイ"], "曇り": ["サクラマス"]},
        "冬": {"晴れ": ["ソイ"], "雨": ["カレイ"], "曇り": ["ホッケ"]},
    },
    "女川港": {
        "春": {"晴れ": ["サクラマス"], "雨": ["ホッケ"], "曇り": ["カレイ"]},
        "夏": {"晴れ": ["ホッケ"], "雨": ["サケ"], "曇り": ["ニシン"]},
        "秋": {"晴れ": ["カレイ"], "雨": ["サワラ"], "曇り": ["ソイ"]},
        "冬": {"晴れ": ["カレイ"], "雨": ["ホッケ"], "曇り": ["サクラマス"]},
    },
    "大洗港": {
        "春": {"晴れ": ["ヒラメ"], "雨": ["アイナメ"], "曇り": ["スズキ"]},
        "夏": {"晴れ": ["スズキ"], "雨": ["ヒラメ"], "曇り": ["メバル"]},
        "秋": {"晴れ": ["アイナメ"], "雨": ["カレイ"], "曇り": ["ヒラメ"]},
        "冬": {"晴れ": ["カレイ"], "雨": ["アイナメ"], "曇り": ["スズキ"]},
    },
    "城ヶ島": {
        "春": {"晴れ": ["メジナ"], "雨": ["クロダイ"], "曇り": ["カサゴ"]},
        "夏": {"晴れ": ["カサゴ"], "雨": ["メバル"], "曇り": ["クロダイ"]},
        "秋": {"晴れ": ["クロダイ"], "雨": ["メジナ"], "曇り": ["カサゴ"]},
        "冬": {"晴れ": ["メバル"], "雨": ["クロダイ"], "曇り": ["メジナ"]},
    },
    "沼津港": {
        "春": {"晴れ": ["アジ"], "雨": ["カツオ"], "曇り": ["メジナ"]},
        "夏": {"晴れ": ["シイラ"], "雨": ["ブリ"], "曇り": ["カマス"]},
        "秋": {"晴れ": ["ヒラマサ"], "雨": ["マダイ"], "曇り": ["アジ"]},
        "冬": {"晴れ": ["メバル"], "雨": ["ヒラメ"], "曇り": ["ブリ"]},
    },
    "串本": {
        "春": {"晴れ": ["メジナ"], "雨": ["クロダイ"], "曇り": ["カサゴ"]},
        "夏": {"晴れ": ["ヒラマサ"], "雨": ["ブリ"], "曇り": ["シイラ"]},
        "秋": {"晴れ": ["アオリイカ"], "雨": ["カマス"], "曇り": ["タチウオ"]},
        "冬": {"晴れ": ["メバル"], "雨": ["カサゴ"], "曇り": ["アジ"]},
    },
    "室戸岬": {
        "春": {"晴れ": ["ブリ"], "雨": ["シイラ"], "曇り": ["カツオ"]},
        "夏": {"晴れ": ["カツオ"], "雨": ["ヒラマサ"], "曇り": ["ブリ"]},
        "秋": {"晴れ": ["タチウオ"], "雨": ["マダイ"], "曇り": ["シーバス"]},
        "冬": {"晴れ": ["ヒラメ"], "雨": ["メバル"], "曇り": ["アジ"]},
    },
    "枕崎": {
        "春": {"晴れ": ["カツオ"], "雨": ["ブリ"], "曇り": ["シイラ"]},
        "夏": {"晴れ": ["シイラ"], "雨": ["マグロ"], "曇り": ["タチウオ"]},
        "秋": {"晴れ": ["マグロ"], "雨": ["カツオ"], "曇り": ["ヒラマサ"]},
        "冬": {"晴れ": ["ブリ"], "雨": ["マダイ"], "曇り": ["シーバス"]},
    },
    "糸満漁港": {
        "春": {"晴れ": ["ミーバイ"], "雨": ["タマン"], "曇り": ["ガーラ"]},
        "夏": {"晴れ": ["カツオ"], "雨": ["ミーバイ"], "曇り": ["シイラ"]},
        "秋": {"晴れ": ["ブリ"], "雨": ["アオリイカ"], "曇り": ["カツオ"]},
        "冬": {"晴れ": ["ヒラメ"], "雨": ["ミーバイ"], "曇り": ["タマン"]},
    },
}

# --- 魚画像＆説明辞書 ---
fish_info = {
    "イワナ": {"img": "https://upload.wikimedia.org/wikipedia/commons/6/66/Iwana01.jpg", "desc": "冷たい清流に住むイワナ。美しい体色が特徴です。"},
    "ヤマメ": {"img": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Yamame_fish.jpg", "desc": "渓流釣りで人気のヤマメ。サケ科の淡水魚です。"},
    "ニジマス": {"img": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Rainbow_trout.png", "desc": "派手な虹色模様をもつ美しい魚。養殖も盛ん。"},
    "アマゴ": {"img": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Amago_fish_2.jpg", "desc": "アマゴは関西地方に多い渓流魚。赤い斑点が特徴。"},
    "オイカワ": {"img": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Oikawa_male.jpg", "desc": "婚姻色が美しい小型淡水魚。群れで泳ぎます。"},
    "フナ": {"img": "https://upload.wikimedia.org/wikipedia/commons/7/75/Carassius_auratus_langsdorfii1.jpg", "desc": "日本全国の池や川にいるおなじみの魚。"},
    "ウグイ": {"img": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Tribolodon_hakonenis_by_OpenCage.jpg", "desc": "幅広い環境に適応できる淡水魚。婚姻色は赤くなる。"},
    "ナマズ": {"img": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Silurus_asotus.jpg", "desc": "夜行性で口ひげが特徴。雷魚と混同されがち。"},
    "ボラ": {"img": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Mugil_cephalus1.jpg", "desc": "汽水域に多く、群れで泳ぐ魚。成魚は大型になります。"},
    "スズキ": {"img": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Lateolabrax_japonicus.jpg", "desc": "釣りでも食でも人気の白身魚。成長と共に名前が変わる出世魚。"},
    "ハゼ": {"img": "https://upload.wikimedia.org/wikipedia/commons/3/33/Acanthogobius_flavimanus.jpg", "desc": "汽水域で釣れる小型魚。天ぷらが美味。"},
    "シーバス": {"img": "https://upload.wikimedia.org/wikipedia/commons/6/66/Lateolabrax_maculatus.jpg", "desc": "ルアー釣りのターゲット。別名スズキ。"},
    "クロダイ": {"img": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Acanthopagrus_schlegelii.jpg", "desc": "磯釣りの代表格。力強い引きが魅力です。"},
    "キス": {"img": "https://upload.wikimedia.org/wikipedia/commons/d/de/Sillago_japonica.jpg", "desc": "砂浜で投げ釣りで狙う人気の魚。白身が上品な味わい。"},
    "アジ": {"img": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Trachurus_japonicus.jpg", "desc": "釣り初心者にも人気の青魚。脂がのった味わい。"},
    "カサゴ": {"img": "https://upload.wikimedia.org/wikipedia/commons/1/15/Sebastiscus_marmoratus.jpg", "desc": "岩礁に潜む小型の根魚。煮付けが美味しい。"},
    "メバル": {"img": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Sebastes_inermis.jpg", "desc": "夜釣りで人気の根魚。暗い所を好む。"},
    "カツオ": {"img": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Katsuwonus_pelamis.jpg", "desc": "回遊魚の代表格。刺身やたたきで人気。"},
    "シイラ": {"img": "https://upload.wikimedia.org/wikipedia/commons/6/60/MahiMahi.png", "desc": "鮮やかな体色が美しい大型魚。夏に多く釣れる。"},
    "ブリ": {"img": "https://upload.wikimedia.org/wikipedia/commons/4/47/Japanese_amberjack.jpg", "desc": "出世魚として有名。冬の寒ブリが特に美味。"},
    "ヒラメ": {"img": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Paralichthys_olivaceus_by_OpenCage.jpg", "desc": "平たい体と隠れる習性。刺身が絶品。"},
    "タチウオ": {"img": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Trichiurus_lepturus2.jpg", "desc": "刀のような見た目。夜釣りの人気者。"},
    "ホッケ": {"img": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Hokke.JPG", "desc": "北海道を中心に釣れる人気魚。焼いて美味しい。"},
    "サバ": {"img": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Scomber_scombrus.jpg", "desc": "青魚の代表格。脂がのって美味しい。"},
    "イナダ": {"img": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Young_Buri_%28Japanese_amberjack%29.jpg", "desc": "ブリの若魚。秋から冬にかけて人気。"},
    "メジナ": {"img": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Girella_lepidota.jpg", "desc": "磯釣りで人気の魚。引きが強い。"},
    "カマス": {"img": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Largehead_cornetfish_(Fistularia_commersonii).jpg", "desc": "細長い体の海水魚。さっぱりとした味。"},
    "アイナメ": {"img": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Ainame_fish.jpg", "desc": "根魚の一種。煮つけにして美味しい。"},
    "ソイ": {"img": "https://upload.wikimedia.org/wikipedia/commons/c/cd/Rockfish_Anoplopoma_fimbria.jpg", "desc": "岩場に生息する根魚。食用に人気。"},
    "シマアジ": {"img": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Striped_jack_%28Caranx_sexfasciatus%29_01.jpg", "desc": "美しい縞模様の強い引きが特徴の魚。"},
    "イサキ": {"img": "https://upload.wikimedia.org/wikipedia/commons/2/29/Ishigaki_Isaki.jpg", "desc": "磯釣りの定番。身が締まって美味。"},
    "タマン": {"img": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Epinephelus_malabaricus.jpg", "desc": "南の海に生息する大型のハタ科魚。強い引き。"},
    "ミーバイ": {"img": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Epinephelus_merra.jpg", "desc": "沖縄近海で人気の根魚。煮付けに良し。"},
    "ガーラ": {"img": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Epinephelus_quoyanus.jpg", "desc": "南西諸島に多い大型魚。引きが強い。"},
    "アオリイカ": {"img": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Aoriika_1.jpg", "desc": "大型のイカ。エギングの対象。"},
    "サクラマス": {"img": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Sakura_Masu.jpg", "desc": "日本のサケの一種。春のターゲット。"},
    "カワハギ": {"img": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Clepticus_parrae_1.jpg", "desc": "皮剥ぎとも呼ばれる。食用に人気。"},
    "ハモ": {"img": "https://upload.wikimedia.org/wikipedia/commons/7/72/Hamo_fish.jpg", "desc": "夏の高級魚。京都の夏の味覚。"},
    "アイゴ": {"img": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Siganus_sutor.jpg", "desc": "毒を持つトゲがある魚。沖縄で釣れる。"},
    "サワラ": {"img": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Sawara_Mackerel.jpg", "desc": "スズキ科の回遊魚。刺身で美味。"},
    "マグロ": {"img": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Thunnus_thynnus_01.jpg", "desc": "大型回遊魚。寿司ネタの王様。"},
    "シマアジ": {"img": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Striped_jack_%28Caranx_sexfasciatus%29_01.jpg", "desc": "高級魚。美しい縞模様が特徴。"},
    "マダイ": {"img": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Pagrus_major_20070124.jpg", "desc": "日本で人気の高級魚。祝いの席でも。"},
    "アキアジ": {"img": "https://upload.wikimedia.org/wikipedia/commons/3/31/Chum_Salmon_on_the_Russian_River_Alaska.jpg", "desc": "秋に遡上するサケ。脂ののりが良い。"},
    "サケ": {"img": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Salmon_in_Capilano_River.jpg", "desc": "食用・釣りともに人気。北の川に多い。"},
    "カラフトマス": {"img": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Oncorhynchus_keta.jpg", "desc": "サケ科の魚。北海道などに多い。"},
}

# --- Streamlit UI ---
st.title("🎣 日本の釣りゲーム 完全版")

location = st.selectbox("釣り場を選択してください", locations)
season = st.selectbox("季節を選択してください", seasons)
weather = st.selectbox("天気を選択してください", weathers)

if st.button("釣りをする！"):
    fish_list = fish_data.get(location, {}).get(season, {}).get(weather, [])
    if not fish_list:
        st.write("この条件では魚が釣れませんでした。")
    else:
        caught = random.choice(fish_list)
        st.success(f"おめでとう！{caught}が釣れました！")

        # 魚画像と説明表示
        info = fish_info.get(caught)
        if info:
            st.image(info["img"], width=300)
            st.write(info["desc"])

# 図鑑ページリンクなど、拡張も可能です